noteSharing/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf import settings

from home import views
from noteSharing import settings
from user import views as UserViews

urlpatterns = [
    path('', include('home.urls')),
    path('note/', include('notes.urls')),
    path('home/', include('home.urls')),
    path('user/', include('user.urls')),
    path(r'^ckeditor/', include('ckeditor_uploader.urls')),

    path('admin/', admin.site.urls),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('category/<int:id>/<slug:slug>/', views.note_list, name='note_list'),
    path('notes/', views.note_list2, name='note_list2'),
    path('note/<int:id>/<slug>/', views.note_details, name='note_detail'),
    path('search/', views.note_search, name="note_search"),
    path('search-auto/', views.note_search_auto, name="note_search"),
    path('login/', UserViews.login_form, name="login_form"),
    path('logout/', UserViews.logout_fun, name="logout_fun"),
    path('register/', UserViews.register_form, name="register_form"),
    path('faq/', UserViews.faq, name="faq"),
    path('downloadpdf//uploads/images/<filename>', views.download_pdf_file_home, name='download_pdf_file_home'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    #path('addcomment/<int:id>', views.addcomment,name='addcomment')
    path('update/', views.user_update, name='ser_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.user_comments, name='user_comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('notes/', views.notes, name="notes"),
    path('addnote/', views.addnote, name='addnote'),
    path('notedelete/<int:id>', views.notedelete, name='notedelete'),
    path('noteedit/<int:id>', views.noteedit, name='noteedit'),
    path('noteaddimage/<int:id>', views.noteaddimage, name='noteaddimage'),
    path('downloadpdf//uploads/images/<filename>', views.download_pdf_file, name='download_pdf_file'),
    #path('downloadpdf//', views.download_pdf_file, name='download_pdf_file'),
]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.forms import ModelForm, TextInput, Textarea


class Setting(models.Model):
    STATUS = (
        ('True' , 'True'),
        ('False' , 'False'),
    )
    title =models.CharField(max_length=200)
    company = models.CharField(max_length=50)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    address = models.TextField(blank=True)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=50)
    smtpemail = models.CharField(blank=True, max_length=50)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    aboutus = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def _str_(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed','Closed'),
    )
    name= models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    phone = models.CharField(blank=True, max_length=20)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS,default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class ContactForm(ModelForm):
    class Meta:
        model=ContactFormMessage
        fields=['name','email','subject','message','phone']
        widgets={
            'name' : TextInput(attrs={'class': 'input', 'placeholder':'Name & Surname'}),
            'subject': TextInput(attrs={'class': 'input', 'placeholder': 'Subject'}),
            'email': TextInput(attrs={'class': 'input', 'placeholder': 'Email Address'}),
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'message': Textarea(attrs={'class': 'input', 'placeholder': 'Your Message','rows':'5'}),
        }

class FAQ(models.Model):
    STATUS = (
        ('True', 'True'),
        ('False', 'False'),
    )
    notenumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

user/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.utils.safestring import mark_safe


class UserProfile(models.Model):
    user= models.OneToOneField(User, on_delete=models.CASCADE)
    phone =models.CharField(blank=True,max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return  self.user.first_name+ ' ' +self.user.first_name+ ' [' +self.user.username + ']'

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'

user/views.py
import mimetypes
import os

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

# Create your views here.
from home.models import Setting, FAQ
from notes.models import Category, Note, Comment, NoteForm, Images, NoteImageForm
from user.forms import SignUpForm, UserUpdateForm, ProfileUpdateForm
from user.models import UserProfile


def index(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(pk=current_user.id)
    context= {'setting': setting,
              'category': category,
              'profile': profile}
    return render(request, 'user_profile.html',context)


def login_form(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # Redirect to a success page.
            current_user = request.user
            userprofile = UserProfile.objects.get(user_id=current_user.id)
            request.session['userimage'] = userprofile.image.url
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, " Login Error")
            return HttpResponseRedirect('/login')
    category = Category.objects.all()
    context = {'category': category,
               }
    return render(request,'login.html',context)


def register_form(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            current_user = request.user
            data = UserProfile()
            data.user_id = current_user.id
            data.image = "images/users/user.jpg"
            data.save()
            messages.success(request, "Registration Completed Successfully")
            return HttpResponseRedirect('/')
        else:
            messages.warning(request, form.errors)
    form = SignUpForm()
    category = Category.objects.all()
    context = {'category': category,
               'form': form,
               }

    return render(request, 'register.html', context)


def logout_fun(request):
    logout(request)
    return HttpResponseRedirect('/')



def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your Profile Has Been Updated')
            return HttpResponseRedirect('/user')
    else:
        category = Category.objects.all()
        current_user = request.user
        profile = UserProfile.objects.get(pk=current_user.id)
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {
            'category': category,
            'user_form': user_form,
            'profile_form': profile_form,
            'profile':profile
        }
        return render(request, 'user_update.html', context)



def change_password(request):
    if request.method=='POST':
        form =PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your Password Has Been Changed')
            return HttpResponseRedirect('/user')
        else:
            messages.error(request, 'Please Fix These Problems<br>'+ str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        category = Category.objects.all()
        form =PasswordChangeForm(request.user)
        return render(request,'change_password.html', {
            'form': form, 'category': category
        })


@login_required(login_url='/login')
def user_comments(request):
    category = Category.objects.all()
    current_user = request.user
    comments = Comment.objects.filter(user_id=current_user.id)
    context = {
        'category': category,
        'comments': comments,
    }
    return render(request, 'user_comment.html', context)


@login_required(login_url='/login')
def deletecomment(request, id):
    current_user =request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Comment Has Been Deleted')
    return HttpResponseRedirect('/user/comments')


def faq(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    faq = FAQ.objects.all().order_by('notenumber')
    context = {'category': category,
               'faq': faq,
               'setting': setting,
               }
    return render(request, 'faq.html', context)




@login_required(login_url='/login')
def addnote(request):
    setting = Setting.objects.get(pk=1)
    if request.method == 'POST':
        form = NoteForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            data = Note()
            data.user_id = current_user.id
            data.category = form.cleaned_data['category']
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            data.file = form.cleaned_data['file']
            data.detail = form.cleaned_data['detail']
            data.slug = form.cleaned_data['slug']
            data.status = 'False'
            data.save()
            messages.success(request, 'Your Content Insterted Successfuly')
            return HttpResponseRedirect('/user/notes')
        else:
            messages.success(request, 'Note Form Error:' + str(form.errors))
            return HttpResponseRedirect('/user/addnote')
    else:
        category = Category.objects.all()
        form = NoteForm()
        context = {
            'category': category,
            'form': form,
            'setting': setting,
        }
        return render(request, 'user_addnote.html', context)

@login_required(login_url='/login')  # Check login
def noteedit(request, id):
    setting = Setting.objects.get(pk=1)
    note = Note.objects.get(id=id)
    if request.method == 'POST':
        form = NoteForm(request.POST, request.FILES, instance=note)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your Note Updated Successfuly')
            return HttpResponseRedirect('/user/notes')
        else:
            messages.success(request, 'Product Form Error: ' + str(form.errors))
            return HttpResponseRedirect('/user/addnote/' + str(id))
    else:
        category = Category.objects.all()
        form = NoteForm(instance=note)
        context = {
            'category': category,
            'form': form,
            'setting': setting,
        }
        return render(request, 'user_addnote.html', context)

@login_required(login_url='/login')  # Check login
def notedelete(request, id):
    current_user = request.user
    Note.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Note deleted...')
    return HttpResponseRedirect('/user/notes')


@login_required(login_url='/login')  # Check login
def notes(request):
    setting = Setting.objects.get(pk=1)
    category = Category.objects.all()
    current_user = request.user
    note = Note.objects.filter( user_id= current_user.id)
    context = {
        'category': category,
        'note': note,
        'setting': setting,
    }
    return render(request, 'user_notes.html', context)



def noteaddimage(request, id):
    if request.method == 'POST':
        lasturl = request.META.get('HTTP_REFERER')
        form = NoteImageForm(request.POST, request.FILES)
        if form.is_valid():
            data = Images()
            data.title = form.cleaned_data['title']
            data.note_id = id
            data.image = form.cleaned_data['image']
            data.save()
            messages.success(request, 'Your image has been successfuly uploaded')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request, 'Form Error: ' + str(form.errors))
            return HttpResponseRedirect(lasturl)
    else:
        note = Note.objects.get(id=id)
        images = Images.objects.filter(note_id=id)
        form = NoteImageForm()
        context = {
            'note': note,
            'images': images,
            'form': form,
        }
        return render(request, 'note_gallery.html', context)


# Define function to download pdf file using template
def download_pdf_file(request, filename):
    category = Category.objects.all()
    context = {'category': category,}
    if filename != '':
        # Define Django project base directory
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        # Define the full file path
        filepath = BASE_DIR + '/uploads/images/' + filename
        # Open the file for reading content
        path = open(filepath, 'rb')
        # Set the mime type
        mime_type, _ = mimetypes.guess_type(filepath)
        # Set the return value of the HttpResponse

user/templates/login.html
{% extends "homebase.html" %}
{% block title %} Login {% endblock %}


{% block content %}
    {% load static %}
  <!-- Start main-content -->
  <div class="main-content">
    <!-- Section: inner-header -->
    <section class="inner-header divider parallax layer-overlay overlay-dark-5" data-bg-img="images/bg/bg6.jpg">
      <div class="container pt-70 pb-20">
        <!-- Section Content -->
        <div class="section-content">
          <div class="row">
            <div class="col-md-12 text-center">
              <h3 class="font-28 text-white">Login/Register</h2>
              <ol class="breadcrumb text-center text-black mt-10">
                <li><a href="#">Home</a></li>
                <li><a href="#">Pages</a></li>
                <li class="active text-gray-silver">Page Title</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2">
            <ul class="nav nav-tabs">
              <li class="active"><a href="#login-tab" data-toggle="tab">Login</a></li>
                <li><a href="#register-tab" data-toggle="tab">Register</a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane fade in active p-15" id="login-tab">
                <h4 class="text-gray mt-0 pt-5"> Login</h4>
                  {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                  {% endif %}
                <hr>
                <p>Lorem ipsum dolor sit amet, consectetur elit.</p>
                <form action="" method="post" name="login-form" class="clearfix">
                    {% csrf_token %}
                  <div class="row">
                    <div class="form-group col-md-12">
                      <label for="form_username_email">Username/Email</label>
                      <input id="username" name="username" class="form-control" type="text">
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col-md-12">
                      <label for="form_password">Password</label>
                      <input id="password" name="password" class="form-control" type="password">
                    </div>
                  </div>
                  <div class="checkbox pull-left mt-15">
                    <label for="form_checkbox">
                      <input id="form_checkbox" name="form_checkbox" type="checkbox">
                      Remember me </label>
                  </div>
                  <div class="form-group pull-right mt-10">
                    <button type="submit" class="btn btn-dark btn-sm">Login</button>
                  </div>
                  <div class="clear text-center pt-10">
                    <a class="text-theme-colored font-weight-600 font-12" href="#">Forgot Your Password?</a>
                  </div>
                  <div class="clear text-center pt-10">
                    <a class="btn btn-dark btn-lg btn-block no-border mt-15 mb-15" href="#" data-bg-color="#3b5998">Login with facebook</a>
                    <a class="btn btn-dark btn-lg btn-block no-border" href="#" data-bg-color="#00acee">Login with twitter</a>
                  </div>
                </form>
              </div>
              <div class="tab-pane fade in p-15" id="register-tab">
                    {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <p>
                                    {{ field.label_tag }} <br>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <small style="color: grey">{{ field.help_text }}</small>
                                    {% endif %}
                                {% for error in field.errors %}
                                    <p style="color:red">{{ error }}</p>
                                {% endfor %}
                                </p>
                            {% endfor %}
                            <button type="submit">Sign Up</button>
                        </form>
{% comment %}                <form action="" name="reg-form" class="register-form" method="post">
                    {% csrf_token %}
                  <div class="icon-box mb-0 p-0">
                    <a href="#" class="icon icon-bordered icon-rounded icon-sm pull-left mb-0 mr-10">
                      <i class="pe-7s-users"></i>
                    </a>
                    <h4 class="text-gray pt-10 mt-0 mb-30">Don't have an Account? Register Now.</h4>
                  </div>
                  <hr>
                  <p class="text-gray">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi id perspiciatis facilis nulla possimus quasi, amet qui. Ea rerum officia, aspernatur nulla neque nesciunt alias.</p>
                  <div class="row">
                    <div class="form-group col-md-6">
                      <label>Name</label>
                      <input name="username" class="form-control" type="text">
                    </div>
                    <div class="form-group col-md-6">
                      <label>Email Address</label>
                      <input name="email" class="form-control" type="email">
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col-md-12">
                      <label for="form_choose_username">Choose Username</label>
                      <input id="form_choose_username" name="form_choose_username" class="form-control" type="text">
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col-md-6">
                      <label for="form_choose_password">Choose Password</label>
                      <input id="form_choose_password" name="password" class="form-control" type="text">
                    </div>
                    <div class="form-group col-md-6">
                      <label>Re-enter Password</label>
                      <input id="form_re_enter_password" name="re_password"  class="form-control" type="text">
                    </div>
                  </div>
                  <div class="form-group">
                    <button class="btn btn-dark btn-lg btn-block mt-15" type="submit">Register Now</button>
                  </div>
                </form>{% endcomment %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
  <!-- end main-content -->
{% endblock %}

user/templates/note_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Note Gallery</title>
</head>
<body>
    <h2>{{ note.title }}</h2>
    <hr>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="note_id" id="id_note_id" value="{{ note.id }}">
        <label for="id_title">Title</label>
        <input type="text" name="title" class="input" placeholder="title" maxlength="50" id="id_title">
        <label for="id_image">Image:</label>
        <input type="file" name="image" class="input" placeholder="image" accept="image/*" id="id_image">
        <button class="btn-primary" type="submit">Upload Image</button>
    </form>
    <hr>
    <h4>Yüklenen Resimler</h4>
    {% for rs in images %}
        <img src="{{ rs.image.url }}" height="200">
    {% endfor %}

</body>
</html>

user/templates/register.html
{% extends "homebase.html" %}
{% block title %} {{ setting.title }} {% endblock %}


{% block content %}
    {% load static %}
  <!-- Start main-content -->
  <div class="main-content">
    <!-- Section: inner-header -->
    <section class="inner-header divider parallax layer-overlay overlay-dark-5" data-bg-img="images/bg/bg6.jpg">
      <div class="container pt-70 pb-20">
        <!-- Section Content -->
        <div class="section-content">
          <div class="row">
            <div class="col-md-12 text-center">
              <h3 class="font-28 text-white">Login/Register</h2>
              <ol class="breadcrumb text-center text-black mt-10">
                <li><a href="#">Home</a></li>
                <li><a href="#">Pages</a></li>
                <li class="active text-gray-silver">Page Title</li>
              </ol>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section>
      <div class="container">
                       {% if messages %}
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }}" role="alert">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <p>
                                    {{ field.label_tag }} <br>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <small style="color: grey">{{ field.help_text }}</small>
                                    {% endif %}
                                {% for error in field.errors %}
                                    <p style="color:red">{{ error }}</p>
                                {% endfor %}
                                </p>
                            {% endfor %}
                            <button type="submit">Sign Up</button>
                        </form>
{% comment %}                <form action="" name="reg-form" class="register-form" method="post">
                    {% csrf_token %}
                  <div class="icon-box mb-0 p-0">
                    <a href="#" class="icon icon-bordered icon-rounded icon-sm pull-left mb-0 mr-10">
                      <i class="pe-7s-users"></i>
                    </a>
                    <h4 class="text-gray pt-10 mt-0 mb-30">Don't have an Account? Register Now.</h4>
                  </div>
                  <hr>
                  <p class="text-gray">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi id perspiciatis facilis nulla possimus quasi, amet qui. Ea rerum officia, aspernatur nulla neque nesciunt alias.</p>
                  <div class="row">
                    <div class="form-group col-md-6">
                      <label>Name</label>
                      <input name="username" class="form-control" type="text">
                    </div>
                    <div class="form-group col-md-6">
                      <label>Email Address</label>
                      <input name="email" class="form-control" type="email">
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col-md-12">
                      <label for="form_choose_username">Choose Username</label>
                      <input id="form_choose_username" name="form_choose_username" class="form-control" type="text">
                    </div>
                  </div>
                  <div class="row">
                    <div class="form-group col-md-6">
                      <label for="form_choose_password">Choose Password</label>
                      <input id="form_choose_password" name="password" class="form-control" type="text">
                    </div>
                    <div class="form-group col-md-6">
                      <label>Re-enter Password</label>
                      <input id="form_re_enter_password" name="re_password"  class="form-control" type="text">
                    </div>
                  </div>
                  <div class="form-group">
                    <button class="btn btn-dark btn-lg btn-block mt-15" type="submit">Register Now</button>
                  </div>
                </form>{% endcomment %}
              </div>
    </section>

  </div>
  <!-- end main-content -->
{% endblock %}

user/templates/user_addnote.html
{% extends "homebase.html" %}
{% block title %} User Comments {% endblock %}


{% block content %}
    {% load static %}
        <div class="span9">
        <div class="well">
            <div class="section-title">
                <h3 class="title">Add Note</h3>
            </div>
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    {{ form.media }}
                    {{ form.as_p }}
                </fieldset>
                <div class="form-group">
                    <button class="btn-primary" type="submit">Save</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}